Lesson4prj/urls.py
from django.contrib import admin
from django.urls import path
from lesson4app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name ="index"),
    path('create/', views.create, name="create"),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>',views.delete),
    path('test/',views.test),
    path('send/',views.email, name="send"),

]

lesson4app/models.py
from django.db import models


# Create your models here.

class Employee(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField("Employee Name", max_length = 100)
    email = models.EmailField("Email Address", max_length=100)
    dob = models.DateTimeField("Date of Birth")
    salary = models.FloatField("Base Salary")

    def __str__(self):
        return self.name

    class Meta:
        db_table = "employees"

lesson4app/forms.py
from django import forms
from .models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"

        widgets = {
                'dob': forms.DateInput(attrs={'class': 'datepicker1 form-control'}),
                'name': forms.TextInput(attrs={'class': 'form-control'}),
                'email': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Email Address'}),
                'salary': forms.TextInput(attrs={'class': 'form-control'})
                }




class ContactForm(forms.Form):
    to      = forms.EmailField(required=True, widget=forms.TextInput(attrs={'class': 'form-control col-sm-4','placeholder': 'Email Address'}))
    subject = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control col-sm-4','placeholder': 'Subject'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control col-sm-4','placeholder': 'Write your Message'}), required=True, label="")

lesson4app/views.py
from django.shortcuts import render, redirect
from .models import Employee
from django.core.paginator import Paginator
from lesson4app.forms import EmployeeForm, ContactForm
from django.contrib import messages
from django.core.mail import BadHeaderError, EmailMessage


# Create your views here.

def index(request):
    emp = Employee.objects.all()


    #employees = Employee.objects.all()
    context = {'title': 'Welcome', 'employees': emp}
    return render(request,"index.html",context)

def create(request):
    if request.method == "POST":
        form= EmployeeForm(request.POST,request.FILES)
        if form.is_valid():
            try:
                form.save()
                messages.error(request,'Insert Successfull')
                return redirect('/index')
                # return redirect('/')
            except:
                pass
        else:
            pass
    else:
        form = EmployeeForm()
    return render(request,'create.html',{'form':form})

def edit(request, id):
    employee=Employee.objects.get(id=id)
    form=EmployeeForm(request.POST,request.FILES)
    return render(request,'edit.html', {'employee':employee,'form':form})

def update(request, id):
    employee=Employee.objects.get(id=id)
    form= EmployeeForm(request.POST,request.FILES,instance=employee)
    if form.is_valid():
        try:
            form.save()
            messages.error(request,'Update Successfull')
            return redirect('/index')
            # return redirect('/')
        except:
            pass
    else:
        messages.error(request,form.error)
    return render(request,'edit.html', {'employee':employee,'form':form})

def delete(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect("/index")


def test(request):
    if request.method == "POST":
        form= EmployeeForm(request.POST,request.FILES)
        if form.is_valid():
            try:
                form.save()
                messages.error(request,'Insert Successfull')
                return redirect('/index')
                # return redirect('/')
            except:
                pass
        else:
            pass
    else:
        form = EmployeeForm()
    return render(request,'test.html',{'form':form})


def email(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():

            subject        = form.cleaned_data['subject']
            form_email     = form.cleaned_data['to']
            message        = form.cleaned_data['message']

            recipient_list = []
            recipient_list.append(form_email)
            try:
                emailobj = EmailMessage(subject, message, to = recipient_list)
                emailobj.send()
            except BadHeaderError:
                return Httpresponse('Invalid header Found')
            return redirect('/index')
    return render(request, "email.html",{'form': form})

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Title{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}" ></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.css"/>
  <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.js"></script>

  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css"/>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

  {% block stylesheet %}{% endblock %}
</head>
<body>
  <div class="">
    <img src="" alt="">
    <img src="{% static 'images/logo.png' %}" alt="No Image" width=100%>
  </div>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/index">(r()s$</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/index">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/create">Add New Employee</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="">Action</a>
            <a class="dropdown-item" href="">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <!-- <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> -->
      </form>
    </div>
  </nav>
  <br><br>
  <main>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
  </main>
  <script>
  $(function () {

  });

  $(function() {
    $('#emptable').DataTable({
      // function for paginator/DataTable.... #=id _____ .=class
      // "dom":'<f<t>ip>',
      "lengthMenu": [[5,10,15,20,25,50,-1],[5,10,15,20,25,50,"All"]]
    });
  });

  $(document).ready(function() {
    $(".datepicker1").datepicker({
      format: "mm/dd/yyyy",
      weekStart:0,
      calenderWeeks: true,
      autoclose: true,
      todayHighlight: true,
      rtl: true,
      oriantation: "auto"
    });
  });

  {% block javascript %}{% endblock %}
  </script>
</body>
</html>

templates/create.html
{% extends 'base.html' %}

{% block title %}Create Employee{% endblock %}
{% block stylesheet %} {% endblock %}
{% block content %}

    <center><form method="POST" class="post-form" action="/create/" enctype="multipart/form-data">
            {% csrf_token %}
        <div class="container">
          <br>
        <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-5">
        <h3>Enter Details</h3>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-3 col-form-label">Employee Name:</label>
        <div class="col-sm-6">
          <!-- <input type="text" name="name" value=""> -->
          {{ form.name }}
        </div>
      </div>
        <div class="form-group row">
        <label class="col-sm-3 col-form-label">Employee Email:</label>
        <div class="col-sm-6">
            <!-- <input type="text" name="email" value=""> -->
            {{ form.email }}
        </div>
      </div>
        <div class="form-group row">
        <label class="col-sm-3 col-form-label">Employee Date of birth:</label>
        <div class="col-sm-6">
            <input type="text" name="dob" value="" class="datepicker1 form-control">
            <!-- {{ form.dob }} -->
        </div>
      </div>
      <div class="form-group row">
    <label class="col-sm-3 col-form-label">Employee Salary:</label>
    <div class="col-sm-6">
        <!-- <input type="text" name="salary" value=""> -->
        {{ form.salary }}
    </div>


  </div>
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-5" align="right">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
        </div>
    </form> </center>

{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% block title %}Edit Employee{% endblock %}
{% block stylesheet %} {% endblock %}
{% block content %}
  <center><form method="POST" class="post-form" action="/update/{{employee.id}}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container">
      <br>
      {% for messages in messages %}
      <div class="alert alert-danger">
        <a class="close" href="#" data-dismiss="alert">Please Insert a valid data. Try again </a>
        {{ message }}
      </div>
      {% endfor %}
      <br>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-5">
          <h3>Edit Employee</h3>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-3 col-form-label">Employee ID:</label>
        <div class="col-sm-6">
          <!-- <input type="text" name="id" value=""> -->
          {{ employee.id }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-3 col-form-label">Employee Name:</label>
        <div class="col-sm-6">
          <input type="text" name="name" id="id_id" required maxlength="20" value="{{ employee.name | upper }}">
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-3 col-form-label">Employee Email:</label>
        <div class="col-sm-6">
          <input type="text" name="email" id="id_id" required maxlength="20" value="{{ employee.email }}">
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-3 col-form-label">Employee Date of birth:</label>
        <div class="col-sm-6">
          <input type="text" name="dob" id="id_id" required maxlength="20" value="{{ employee.dob | date:"m/d/y" }}">
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-3 col-form-label">Employee Salary:</label>
        <div class="col-sm-6">
          <input type="text" name="salary" id="id_id" required maxlength="20" value="{{ employee.salary | floatformat:"3" }}">
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-5" align="right">
          <button type="submit" class="btn btn-primary" >Submit</button>
        </div>
      </div>
    </div>
  </form> </center>
{% endblock %}

templates/email.html
{% extends 'base.html' %}

{% block title %}Email{% endblock %}
{% block stylesheet %} {% endblock %}
{% block content %}

<h1>Contact Us</h1>
<form method="POST">
  {% csrf_token %}
  {% for field in form %}
    <div class="form-group row">
      {{ field.error }}
      <label class="col-sm-2 col-form-label" for="{{ field.name }}">{{ field.label_tag }}</label>
      <!-- {{ field.lable_tag }} -->
      {{ field }}
      {% if field.help_text %}
      <p class="help">{{field.help_text|safe}}</p>
      {% endif %}

    </div>
  {% endfor %}
  <div class="form-action">
    <button type="submit" name="button">send</button>
  </div>

</form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}
{% block stylesheet %} {% endblock %}
{% block content %}

    <table class="table table-bordered" id="emptable" data-page-length="5">
      <thead class='table-dark'>
        <tr>
          <td>Id</td>
          <td>Name</td>
          <td>Date of Birth</td>
          <td>Email</td>
          <td>Salary</td>
          <td>Actions</td>
        </tr>
      </thead>
      <tbody>
        {% for emp in employees %}
        <tr>
          <td>{{emp.id}}</td>
          <td>{{emp.name}}</td>
          <td>{{emp.dob | date:"m/d/Y" }}</td>
          <td>{{emp.email}}</td>
          <td>{{emp.salary | floatformat:"-3" }}</td>
          <td>
              <a href="/edit/{{ emp.id }}">Edit</a> |
              <a href="/delete/{{ emp.id }}">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <br>

      <br>
      <p align="right"><a href="/create" class="btn btn-primary">Add New Record</a></p>
      <br><br>

{% endblock %}

templates/test.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}
{% block stylesheet %} {% endblock %}
{% block content %}
<form method="POST" class="post-form"  enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" name="button">Submit</button>
</form>
{% endblock %}